### ISSUE TITLE
PHP backdoor

### ISSUE THREAD

**Issue by Te-k** [museomix/museomix.org#35]
Hi museomix,

There is a php backdoor in your website here : museomix.org/wp-content/plugins/w3-total-cache/inc/functions/index.phtml (and it is also available on the website), which means that your website was compromised.
You should defiinitely have a look at this (contact me by email if you need infos)
Cheers
Tek

**Comment by samy** [comment]
Thanks, we fixed it !

**Comment by Te-k** [comment]
You should make an analysis of the whole website, if it has been compromised, there are likely backdoors in other places.
Like this one : ./wp-content/plugins/w3-total-cache/lib/W3/Cache/File/content.phtml: misc_php_backdoor

**Comment by Te-k** [comment]
Or pharmacy ads in your template : ./wp-content/themes/museomix-design-2/header.php: pharmacy, hidden

**Comment by samy** [comment]
Thanks !
